# Generated by Django 3.0.8 on 2020-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0011_auto_20200605_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
